name: ci-cd-pipeline

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        
      - name: Run lint check
        run: npm run lint
        
      - name: Check web standards
        run: npm run validate
        
      - name: Run Tests
        run: npm test -- --passWithNoTests

      - name: Create env file
        run: |
          touch .env
          echo "REACT_APP_TMDB_API_KEY=${{ secrets.REACT_APP_TMDB_API_KEY }}" >> .env
          echo "REACT_APP_KAKAO_API_KEY=${{ secrets.REACT_APP_KAKAO_API_KEY }}" >> .env
          echo "REACT_APP_CLIENT_VERSION=${{ secrets.REACT_APP_CLIENT_VERSION }}" >> .env
          echo "IMAGE_URL=${{ secrets.IMAGE_URL }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "REACT_APP_HOMEPAGE=${{ secrets.REACT_APP_HOMEPAGE }}" >> .env
          echo "PUBLIC_URL=${{ secrets.PUBLIC_URL }}" >> .env

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          
      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          touch .env-prod
          echo "REACT_APP_TMDB_API_KEY=${{ secrets.REACT_APP_TMDB_API_KEY }}" >> .env-prod
          echo "REACT_APP_KAKAO_API_KEY=${{ secrets.REACT_APP_KAKAO_API_KEY }}" >> .env-prod
          echo "REACT_APP_CLIENT_VERSION=${{ secrets.REACT_APP_CLIENT_VERSION }}" >> .env-prod
          echo "IMAGE_URL=${{ secrets.IMAGE_URL }}" >> .env-prod
          echo "PORT=${{ secrets.PORT }}" >> .env-prod
          echo "REACT_APP_HOMEPAGE=${{ secrets.REACT_APP_HOMEPAGE }}" >> .env-prod
          echo "PUBLIC_URL=${{ secrets.PUBLIC_URL }}" >> .env-prod

      - name: Build
        run: npm run build:prod

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment